### ISSUE TITLE
大佬是怎么解决嘴型和语音的同步问题的？

### ISSUE THREAD

**Issue by lvyonghuan** [cdfmlr/live2dview#2]
看到上一个commit有点好奇，我们被这个问题困扰老久了，只是大概处理了下

能说下思路吗（

**Comment by cdfmlr** [comment]
我这边是用了一个大佬写的 fork: https://github.com/RaSan147/pixi-live2d-display

**Comment by lvyonghuan** [comment]
> 我这边是用了一个大佬写的 fork: https://github.com/RaSan147/pixi-live2d-display

好的，感谢，我去看看
